/*
Generated by scripts/gen_sprite_data.py at 2025-12-14 00:11:51
Seek head : 256
Memory Offset : 0x200000
*/

	
#ifndef SPRITES_H
#define SPRITES_H

#include "kernel/util.h"
#include "graphics/pomelo.h"


	extern struct SpriteSheet cat0_sprites;
extern struct SpriteSheet cat1_sprites;
extern struct SpriteSheet cat2_sprites;
extern struct SpriteSheet cat3_sprites;
extern struct SpriteSheet level0_sprites;

	
void init_sprites();
#endif

		