#include "kernel/util.h"

#define CH_ESCAPE       0xF0
#define CH_EXTENDED     0xE0

#define KEY_UNKNOWN     0x00

/* Single Byte Key Codes */
#define KEY_NUM      0x77
#define KEY_SCROLL   0x7E
#define KEY_CAPS     0x58
#define KEY_LSHIFT   0x12
#define KEY_RSHIFT   0x59
/* This is Left CTRL and ALT but Right version is in E0 with same code */
#define KEY_LCTRL     0X14
#define KEY_LALT      0x11

/* Temporary definitions*/
#define KEY_RCTRL 0x14
#define KEY_RALT 0x11
/* Generated by some keyboards by ALT and PRTSCR */
#define KEY_SYSRQ    0x84
#define KEY_ESC      0x76
#define KEY_BACKSPACE       0x66
#define KEY_TAB      0x0D
#define KEY_RETURN    0x5A
#define KEY_SPACE    0x29
#define KEY_KP0      0x70
#define KEY_KP1      0x69
#define KEY_KP2      0x72
#define KEY_KP3      0x7A
#define KEY_KP4      0x6B
#define KEY_KP5      0x73
#define KEY_KP6      0x74
#define KEY_KP7      0x6C
#define KEY_KP8      0x75
#define KEY_KP9      0x7D
#define KEY_KP_DOT   0x71
#define KEY_KP_ADD  0x79
#define KEY_KP_SUB 0x7B
#define KEY_KP_MUL 0x7C
/* Some keyboards have an '=' on right keypad */
#define KEY_KP_EQUAL 0x0F
#define KEY_0        0X45
#define KEY_1        0X16
#define KEY_2        0X1E
#define KEY_3        0X26
#define KEY_4        0X25
#define KEY_5        0X2E
#define KEY_6        0X36
#define KEY_7        0X3D
#define KEY_8        0X3E
#define KEY_9        0X46
#define KEY_APOSTROPHE     0X52
#define KEY_COMMA    0X41
#define KEY_MINUS    0X4E
#define KEY_DOT      0X49
#define KEY_SLASH      0X4A

/* Single quote or back apostrophe */
#define KEY_BACKTICK     0X0E
#define KEY_A        0X1C
#define KEY_B        0X32
#define KEY_C        0X21
#define KEY_D        0X23
#define KEY_E        0X24
#define KEY_F        0X2B
#define KEY_G        0X34
#define KEY_H        0X33
#define KEY_I        0X43
#define KEY_J        0X3B
#define KEY_K        0X42
#define KEY_L        0X4B
#define KEY_M        0X3A
#define KEY_N        0X31
#define KEY_O        0X44
#define KEY_P        0X4D
#define KEY_Q        0X15
#define KEY_R        0X2D
#define KEY_S        0X1B
#define KEY_T        0X2C
#define KEY_U        0X3C
#define KEY_V        0X2A
#define KEY_W        0X1D
#define KEY_X        0X22
#define KEY_Y        0X35
#define KEY_Z        0X1A
#define KEY_SEMICOLON    0X4C
#define KEY_BACKSLASH    0X5D
// Extra key left of Z on 102 keyboards
#define KEY_EUROPE2  0x61
#define KEY_LBRACKET  0X54
#define KEY_RBRACKET 0X5B
#define KEY_EQUALS    0X55
#define KEY_F1       0X05
#define KEY_F2       0X06
#define KEY_F3       0X04
#define KEY_F4       0X0C
#define KEY_F5       0X03
#define KEY_F6       0X0B
#define KEY_F7       0X83
#define KEY_F8       0X0A
#define KEY_F9       0X01
#define KEY_F10      0X09
#define KEY_F11      0X78
#define KEY_F12      0X07
#define KEY_F13      0X08
#define KEY_F14      0X10
#define KEY_F15      0X18
#define KEY_F16      0X20
#define KEY_F17      0X28
#define KEY_F18      0X30
#define KEY_F19      0X38
#define KEY_F20      0X40
#define KEY_F21      0X48
#define KEY_F22      0X50
#define KEY_F23      0X57
#define KEY_F24      0X5F
#define KEY_KP_COMMA 0X6D
#define KEY_INTL1    0X51
#define KEY_INTL2    0X13
#define KEY_INTL3    0X6A
#define KEY_INTL4    0X64
#define KEY_INTL5    0X67
#define KEY_LANG1    0XF2
#define KEY_LANG2    0XF1
#define KEY_LANG3    0X63
#define KEY_LANG4    0X62
#define KEY_LANG5    0X5F

/* Extended key codes E0 table for two byte codes */
/* PS2_CTRL and PS2_ALT Need using in any table for the right keys */
/* first is special case for PRTSCR not always used so ignored by decoding */
#define KEY_IGNORE   0x12
#define KEY_PRTSCR   0x7C
/* Sometimes called windows key */
#define KEY_LSUPER   0x1F
#define KEY_RSUPER   0x27
#define KEY_MENU     0x2F
/* Break is CTRL + PAUSE generated inside keyboard */
#define KEY_BREAK    0x7E
#define KEY_HOME     0x6C
#define KEY_END      0x69
#define KEY_PGUP     0x7D
#define KEY_PGDN     0x7A
#define KEY_L_ARROW  0x6B
#define KEY_R_ARROW  0x74
#define KEY_UP_ARROW 0x75
#define KEY_DN_ARROW 0x72
#define KEY_INSERT   0x70
#define KEY_DELETE   0x71
#define KEY_KP_ENTER 0x5A
#define KEY_KP_DIV   0x4A
#define KEY_NEXT_TR  0X4D
#define KEY_PREV_TR  0X15
#define KEY_STOP     0X3B
#define KEY_PLAY     0X34
#define KEY_MUTE     0X23
#define KEY_VOL_UP   0X32
#define KEY_VOL_DN   0X21
#define KEY_MEDIA    0X50
#define KEY_EMAIL    0X48
#define KEY_CALC     0X2B
#define KEY_COMPUTER 0X40
#define KEY_WEB_SEARCH  0X10
#define KEY_WEB_HOME    0X3A
#define KEY_WEB_BACK    0X38
#define KEY_WEB_FORWARD 0X30
#define KEY_WEB_STOP    0X28
#define KEY_WEB_REFRESH 0X20
#define KEY_WEB_FAVOR   0X18
#define KEY_POWER    0X37
#define KEY_SLEEP    0X3F
#define KEY_WAKE     0X5E

struct KeyMap {
	u8 base[128];
	u8 shift[128];
	u8 numlock[128];
};

extern const struct KeyMap kbd_map;

